import ".//globals.scss";



export const metadata = {
  title : "Create Next App", description : "Generated by create next app", link : "https://use.typekit.net/ptz3vfb.css",
  
}

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
      <body>{children}</body>
    </html>
  )
}
